### ISSUE TITLE
Name and Repo?

### ISSUE THREAD

**Issue by rendbs** [jairoxyz/kodistuff#4]
Jairoxyz

Fantastic work!! 

Is there any chance you can change the name of it to SPORTSDEVIL_JXYZ to denote your version or something like that as the problem I'm having at the moment is it is being over written with other versions
Of Sports Devil. Just thought if you changed the name in the addon.xml it wouldn't look for that update anymore. 

Also is there any chance of putting your zip in a repo so it updates automatically?

**Comment by Alexandersss** [comment]
The latest version has some problems. Installation error due to erroneous dependence.
In addition, you should update all the links on Rojadirecta and even livetv.ru does not seem to work. Instead in the official version of March 2017, everything works regularly.

**Comment by jairoxyz** [comment]
Rename is a bad idea because I'll have problems with plugin calls from lspro for ex. Just give it a high version number in addon.xml or disable auto-update. TVA is maintaining a repo here https://offshoregit.com/unofficialsportsdevil .

**Comment by jairoxyz** [comment]
For the erroneous dependence we'd need to see the log file. Maybe f4mproxy is the problem.

**Comment by jairoxyz** [comment]
livetv.ru works for me. what is your error? I am not maintaining rojadirecta.

**Comment by Alexandersss** [comment]
Ok, now in your last update, installation has been successful and livetv.tu works.
For Rojadirecta you can not do anything? For example, if you want to see the MotoGP, the links seem all offline or appear to start loading and then stop. However, the same links work smoothly on the site. :/

**Comment by sattekop** [comment]
for bonanza and sd you can contact me via bonanzakodi@protonmail.com

**Comment by sattekop** [comment]
Jairox, is there a board where users could exchange comments in absence of TVA?

**Comment by Alexandersss** [comment]
However livetv.ru works on Windows, but it does not work on Android. I tried both on smartphones and on tv boxes and this error (web request failed)

**Comment by jairoxyz** [comment]
For livetvru you might need a patched version of librtmp. For Android I recommend to install SPMC or similar flair of Kodi.

**Comment by jairoxyz** [comment]
Lets give them a few more days to get TVA back then we can start thinking of alternatives...

**Comment by jairoxyz** [comment]
OK, good. The TVA devs are still waiting for news from TVA admin but think the site will come up again. Lets wait a few days more and think of alternatives.

sattekop <notifications@github.com> wrote:
for bonanza and sd you can contact me via bonanzakodi@protonmail.com
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jairoxyz/kodistuff","title":"jairoxyz/kodistuff","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jairoxyz/kodistuff"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sattekop in #4: for bonanza and sd you can contact me via bonanzakodi@protonmail.com"}],"action":{"name":"View Issue","url":"https://github.com/jairoxyz/kodistuff/issues/4#issuecomment-309229210"}}}
